language: node_js
node_js: node
cache: yarn
env:
  - CONTINUOUS_INTEGRATION=true
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
script:
  - yarn test:lint
  - yarn cross-env NODE_ENV=test karma start
